import assert from 'node:assert/strict';
import fs from 'node:fs';
import {EVENT_IDS,loadDependencyRegistry,processEventResourceRequests,buildEventResourceProjection} from './process_event_resource_requests.mjs';
import {buildSourceChangeCommand} from './projection_persistence_adapters.mjs';
const registry=loadDependencyRegistry();
let state=JSON.parse(fs.readFileSync(new URL('../contracts/cudo-event-resource-governed-fixture-v1.json',import.meta.url),'utf8'));
let tick=0;const now=()=> '2026-09-22T06:'+String(tick++).padStart(2,'0')+':00.000Z';
const req=(id,event,action,payload)=>({request_id:id,requested_at:now(),event_id:event,expected_revision:state.store_revision,action,payload,requested_by:'sistemas@cudo.cl',reason:'QA '+action,evidence_ref:'qa://'+id});
const apply=(id,event,action,payload={})=>{const r=processEventResourceRequests({requests:[req(id,event,action,payload)],stateStore:state,registry,now});state=r.state_store;assert.equal(r.summary[0].status,'APPLIED');return r;};

let r=apply('M-OFFER-C',EVENT_IDS.MATCH,'MATCH_ADD_OFFERING',{name:'Completo QA',mode:'PREPARED',sell_price:2500});
apply('M-ING-PAN',EVENT_IDS.MATCH,'MATCH_ADD_INGREDIENT',{offering_id:'OFFER-COMPLETO_QA',item_name:'Pan',qty_per_sale:1,unit:'unidad'});
apply('M-ING-VIE',EVENT_IDS.MATCH,'MATCH_ADD_INGREDIENT',{offering_id:'OFFER-COMPLETO_QA',item_name:'Vienesa',qty_per_sale:1,unit:'unidad'});
apply('M-OFFER-B',EVENT_IDS.MATCH,'MATCH_ADD_OFFERING',{name:'Bebida lata QA',mode:'DIRECT_RESALE',sell_price:1500});
for(const [id,item,cost] of [['M-P-PAN','INV-PAN',300],['M-P-VIE','INV-VIENESA',400],['M-P-BEV','INV-BEBIDA_LATA_QA',700]]) r=apply(id,EVENT_IDS.MATCH,'MATCH_PURCHASE',{item_id:item,qty:10,unit_cost:cost,supplier:'Proveedor QA',payment:'PENDING'});
assert.equal(r.projection.MATCH.commerce.purchase_total,14000);
assert.equal(r.projection.MATCH.supplier_payable.amount,14000);
r=apply('M-S-C',EVENT_IDS.MATCH,'MATCH_SALE',{offering_id:'OFFER-COMPLETO_QA',qty:2,unit_price:2500,method:'CASH'});
assert.equal(r.projection.MATCH.commerce.inventory_items.find(x=>x.item_id==='INV-PAN').stock,8);
assert.equal(r.projection.MATCH.commerce.inventory_items.find(x=>x.item_id==='INV-VIENESA').stock,8);
r=apply('M-S-B',EVENT_IDS.MATCH,'MATCH_SALE',{offering_id:'OFFER-BEBIDA_LATA_QA',qty:3,unit_price:1500,method:'CASH'});
assert.equal(r.projection.MATCH.commerce.inventory_items.find(x=>x.item_id==='INV-BEBIDA_LATA_QA').stock,7);
assert.equal(r.projection.MATCH.commerce.sales_revenue,9500);

const stale={...req('STALE',EVENT_IDS.MATCH,'MATCH_SALE',{offering_id:'OFFER-BEBIDA_LATA_QA',qty:1,unit_price:1500,method:'CASH'}),expected_revision:state.store_revision-1};
const before=JSON.stringify(state.objects);const blocked=processEventResourceRequests({requests:[stale],stateStore:state,registry,now});assert.equal(blocked.summary[0].status,'BLOCKED_REVISION_CONFLICT');assert.equal(JSON.stringify(blocked.state_store.objects),before);state=blocked.state_store;
r=apply('M-RESULT',EVENT_IDS.MATCH,'MATCH_RESULT',{series:'Primera',home:2,away:1});
apply('B-PERMIT',EVENT_IDS.BINGO,'BINGO_CONFIRM_PERMIT',{reference:'AUT-QA'});
apply('B-PRIZE',EVENT_IDS.BINGO,'BINGO_DONATE_PRIZE',{name:'Canasta',reference:'DON-QA'});
apply('B-OFFER',EVENT_IDS.BINGO,'BINGO_ADD_OFFERING',{name:'Empanada lista QA',mode:'DIRECT_RESALE',sell_price:2000});
apply('B-PUR',EVENT_IDS.BINGO,'BINGO_PURCHASE',{item_id:'INV-EMPANADA_LISTA_QA',qty:8,unit_cost:900,supplier:'Proveedor QA',payment:'PENDING'});
r=apply('B-SALE',EVENT_IDS.BINGO,'BINGO_SALE',{offering_id:'OFFER-EMPANADA_LISTA_QA',qty:4,unit_price:2000,method:'CASH'});
assert.equal(r.projection.BINGO.commerce.inventory_items.find(x=>x.item_id==='INV-EMPANADA_LISTA_QA').stock,4);
assert.equal(r.projection.BINGO.commerce.sales_revenue,8000);assert.equal(r.projection.BINGO.supplier_payable.amount,7200);
apply('M-CLOSE',EVENT_IDS.MATCH,'MATCH_CLOSE',{});r=apply('B-CLOSE',EVENT_IDS.BINGO,'BINGO_CLOSE',{});
const final=buildEventResourceProjection(state);assert.equal(final.commerce_model,'DYNAMIC_EVENT_OFFERINGS_RECIPE_AND_RESALE');assert.equal(final.MATCH.commerce.offerings.length,2);assert.equal(final.BINGO.commerce.offerings.length,1);assert.equal(final.production_write,false);
const event=state.objects.find(x=>x.object_id===EVENT_IDS.MATCH);
assert.throws(()=>buildSourceChangeCommand({objects:state.objects,surface:'CUDO_WEB_EVENT_RESOURCE_QA',objectId:event.object_id,field:'sales_revenue',value:999,requestedBy:'sistemas@cudo.cl',reason:'negative control',evidenceRefs:['qa://negative']}),/direct surface write blocked/);
const applied=state.audit.filter(x=>x.status==='APPLIED');assert.ok(applied.length>=14);assert.ok(applied.every(x=>x.transaction_id));
console.log(JSON.stringify({schema_version:'CUDO_EVENT_RESOURCE_GOVERNED_PERSISTENCE_CERT_V2',pass:true,final_revision:state.store_revision,applied_requests:applied.length,dynamic_offerings:true,prepared_recipe_consumption:true,direct_resale_consumption:true,stale_revision_fail_closed:true,production_write:false},null,2));
