import fs from 'node:fs';

const CLIENT_ID=process.env.CUDO_GOOGLE_OAUTH_CLIENT_ID;
const CLIENT_SECRET=process.env.CUDO_GOOGLE_OAUTH_CLIENT_SECRET;
const REFRESH_TOKEN=process.env.CUDO_GOOGLE_REFRESH_TOKEN;
for(const [name,value] of Object.entries({CLIENT_ID,CLIENT_SECRET,REFRESH_TOKEN})) if(!value) throw new Error(`${name} no configurado`);

const REVIEW_SHEET_ID='1KnC56IWf2hRxrGU4ksdO-JlzWyl2XJbhbOHKkdx4vms';
const MODULES={NOTICIA:{spreadsheetId:'14ZCRIuCBtZQ_obcXzxYY3FKDScSMZG1v7UZ0954nwJI',sheet:'PUBLICO_EXPORT'},EQUIPO:{spreadsheetId:'1GJYChKXx9qAwBu7fhC8V-qmoW5S1Mmq7kP8cuO6khNI',sheet:'PUBLICO_EXPORT'},PLANTEL:{spreadsheetId:'1fvJedi1WiI_lm-WFGXls4STjddAcdz3_wQN8GG11B94',sheet:'PUBLICO_EXPORT'},PARTIDO:{spreadsheetId:'1AiIAh-gjtiWRTGoMAnhF-iN83XB4cWSgbeEUX_C7VbI',sheet:'PUBLICO_EXPORT'},TABLA:{spreadsheetId:'1evGNco6Si1BYUAdwsBxLGiSMsYEmmojVWlx04NgPodY',sheet:'PUBLICO_EXPORT'},GALERIA:{spreadsheetId:'1RDs5qukBJnW8L6OBPwo4ZcB3a3xz3tI2XibceTh6Q2c',sheet:'PUBLICO_EXPORT'}};

async function token(){const body=new URLSearchParams({client_id:CLIENT_ID,client_secret:CLIENT_SECRET,refresh_token:REFRESH_TOKEN,grant_type:'refresh_token'});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const d=await r.json();if(!r.ok||!d.access_token)throw new Error(`OAuth refresh falló HTTP ${r.status}: ${d.error_description||d.error||'desconocido'}`);return d.access_token}
async function readValues(accessToken,spreadsheetId,range,render='FORMATTED_VALUE'){const u=`https://sheets.googleapis.com/v4/spreadsheets/${spreadsheetId}/values/${encodeURIComponent(range)}?majorDimension=ROWS&valueRenderOption=${render}`;const r=await fetch(u,{headers:{Authorization:`Bearer ${accessToken}`}});const d=await r.json();if(!r.ok)throw new Error(`Sheets read ${spreadsheetId}/${range} HTTP ${r.status}: ${d.error?.message||'desconocido'}`);return d.values||[]}
async function spreadsheetMetadata(accessToken,spreadsheetId){const fields=encodeURIComponent('properties(title),sheets(properties(sheetId,title,index,hidden,gridProperties(rowCount,columnCount)))');const u=`https://sheets.googleapis.com/v4/spreadsheets/${spreadsheetId}?includeGridData=false&fields=${fields}`;const r=await fetch(u,{headers:{Authorization:`Bearer ${accessToken}`}});const d=await r.json();if(!r.ok)throw new Error(`Sheets metadata ${spreadsheetId} HTTP ${r.status}: ${d.error?.message||'desconocido'}`);return d}
function rows(values){return values.slice(1).filter(r=>r.some(v=>String(v??'').trim()!==''))}
function headers(values){return values[0]?.map(v=>String(v||'').trim()).filter(Boolean)||[]}
function nonSensitiveSamples(values,exclude,maxRows=3){if(!values.length)return[];const h=values[0].map(v=>String(v||'').trim());const excluded=new Set(exclude);return rows(values).slice(0,maxRows).map(row=>Object.fromEntries(h.map((name,i)=>[name,String(row[i]??'').trim()]).filter(([name])=>name&&!excluded.has(name))))}
function distinctCounts(values,headerNames){if(!values.length)return{};const h=values[0].map(v=>String(v||'').trim()),idx=Object.fromEntries(h.map((x,i)=>[x,i])),out={};for(const name of headerNames){if(idx[name]===undefined)continue;const counts={};for(const row of rows(values)){const v=String(row[idx[name]]??'').trim()||'(vacío)';counts[v]=(counts[v]||0)+1}out[name]=counts}return out}
function compactRows(values,maxRows=100){return values.slice(0,maxRows).map(row=>row.map(v=>String(v??'').trim()))}
function colName(n){let s='';for(let x=n+1;x;x=Math.floor((x-1)/26))s=String.fromCharCode(65+(x-1)%26)+s;return s}
function formulaCells(values){const out=[];values.forEach((row,r)=>row.forEach((v,c)=>{const s=String(v??'').trim();if(s.startsWith('='))out.push({cell:`${colName(c)}${r+1}`,formula:s})}));return out}

const accessToken=await token();
const reviewMetadata=await spreadsheetMetadata(accessToken,REVIEW_SHEET_ID);const reviewSheetTitles=(reviewMetadata.sheets||[]).map(s=>s.properties?.title).filter(Boolean);const audit=await readValues(accessToken,REVIEW_SHEET_ID,'AUDITORIA_REVISION!A:P');if(!audit.length)throw new Error('AUDITORIA_REVISION sin encabezados');const auditHeaders=audit[0].map(v=>String(v||'').trim()),idx=Object.fromEntries(auditHeaders.map((h,i)=>[h,i]));for(const h of ['ID_REVISION','TIPO_CONTENIDO','IDENTIFICADOR_HUMANO','DECISION','ESTADO_PROCESO'])if(idx[h]===undefined)throw new Error(`Falta columna ${h} en AUDITORIA_REVISION`);const pending=rows(audit).filter(row=>Boolean(String(row[idx.IDENTIFICADOR_HUMANO]||'').trim()&&String(row[idx.TIPO_CONTENIDO]||'').trim()&&String(row[idx.DECISION]||'').trim()&&!String(row[idx.ESTADO_PROCESO]||'').trim()));const countsByType={};for(const row of pending){const type=String(row[idx.TIPO_CONTENIDO]||'').trim()||'(vacío)';countsByType[type]=(countsByType[type]||0)+1}const historicalTypes={};for(const row of rows(audit)){const type=String(row[idx.TIPO_CONTENIDO]||'').trim();if(type)historicalTypes[type]=(historicalTypes[type]||0)+1}const reviewConfig={};for(const title of reviewSheetTitles.filter(t=>/FORM_SPEC|CATALOG|CONFIG|README|SPEC/i.test(t)))reviewConfig[title]=compactRows(await readValues(accessToken,REVIEW_SHEET_ID,`${title}!A:Z`));

const modules={};
for(const [key,module] of Object.entries(MODULES)){
  const metadata=await spreadsheetMetadata(accessToken,module.spreadsheetId),sheetTitles=(metadata.sheets||[]).map(s=>s.properties?.title).filter(Boolean),publicValues=await readValues(accessToken,module.spreadsheetId,`${module.sheet}!A:Z`),revision=sheetTitles.includes('REVISION')?await readValues(accessToken,module.spreadsheetId,'REVISION!A:H'):[],control=sheetTitles.includes('CONTROL')?await readValues(accessToken,module.spreadsheetId,'CONTROL!A:Z'):[],corrections=sheetTitles.includes('CORRECCIONES')?await readValues(accessToken,module.spreadsheetId,'CORRECCIONES!A:Z'):[],formSpec=sheetTitles.includes('FORM_SPEC')?await readValues(accessToken,module.spreadsheetId,'FORM_SPEC!A:Z'):[],controlFormula=sheetTitles.includes('CONTROL')?await readValues(accessToken,module.spreadsheetId,'CONTROL!A1:Z5','FORMULA'):[],publicFormula=await readValues(accessToken,module.spreadsheetId,`${module.sheet}!A1:Z5`,'FORMULA');
  modules[key]={spreadsheet_title:metadata.properties?.title||null,sheet_titles:sheetTitles,raw_form_sheets:sheetTitles.filter(title=>/^RAW_FORM_/i.test(title)),control_headers:headers(control),revision_rows:rows(revision).length,revision_headers:headers(revision),revision_state_samples:nonSensitiveSamples(revision,['ID','REVISOR','FECHA_REVISION','OBSERVACIONES']),corrections_rows:rows(corrections).length,corrections_headers:headers(corrections),corrections_state_counts:distinctCounts(corrections,['DECISION','ACCION','ESTADO','ESTADO_PROCESO','TIPO_CAMBIO','CAMPO_CORRECCION','PUBLICAR','PRIVACIDAD','AUTORIZACION_PUBLICACION','AUTORIZACION_MENORES']),corrections_samples:nonSensitiveSamples(corrections,['ID','ID_CORRECCION','IDENTIFICADOR_HUMANO','NUEVO_VALOR','VALOR_ANTERIOR','OBSERVACIONES','REVISOR','RESPONSABLE','FECHA','FECHA_REVISION']),form_spec:compactRows(formSpec),formula_contract:{control:formulaCells(controlFormula),public_export:formulaCells(publicFormula)},public_export_rows:rows(publicValues).length,public_export_headers:headers(publicValues)};
}
const galleryId=MODULES.GALERIA.spreadsheetId,galleryControl=await readValues(accessToken,galleryId,'CONTROL!A:Z'),galleryRevision=await readValues(accessToken,galleryId,'REVISION!A:H'),galleryCatalogs=await readValues(accessToken,galleryId,'CATALOGOS!A:Z'),galleryFormSpec=await readValues(accessToken,galleryId,'FORM_SPEC!A:Z');const galleryContract={control_state_counts:distinctCounts(galleryControl,['CONTIENE_MENORES','AUTORIZACION_MENORES','ESTADO_REGISTRO','PUBLICAR','PRIVACIDAD','AUTORIZACION_PUBLICACION']),revision_state_counts:distinctCounts(galleryRevision,['ESTADO','PUBLICAR','PRIVACIDAD','AUTORIZACION_PUBLICACION','AUTORIZACION_MENORES']),review_audit_authorization_counts:distinctCounts(audit,['AUTORIZACION_PUBLICACION','AUTORIZACION_MENORES']),catalogs:compactRows(galleryCatalogs),form_spec:compactRows(galleryFormSpec)};
const report={ok:true,mode:'READ_ONLY_NO_EXTERNAL_WRITES',timestamp:new Date().toISOString(),review_sheet:{title:reviewMetadata.properties?.title||null,sheet_titles:reviewSheetTitles,headers:auditHeaders,audit_rows:rows(audit).length,historical_types:historicalTypes,pending_decisions:pending.length,pending_by_type:countsByType,decision_counts:distinctCounts(audit,['DECISION','AUTORIZACION_PUBLICACION','AUTORIZACION_MENORES','ESTADO_PROCESO','RESULTADO','CAMPO_CORRECCION']),configuration:reviewConfig},modules,gallery_contract:galleryContract};fs.mkdirSync('qa-review-probe',{recursive:true});fs.writeFileSync('qa-review-probe/read-only-report.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
