import fs from 'node:fs';
const CLIENT_ID=process.env.CUDO_GOOGLE_OAUTH_CLIENT_ID,CLIENT_SECRET=process.env.CUDO_GOOGLE_OAUTH_CLIENT_SECRET,REFRESH_TOKEN=process.env.CUDO_GOOGLE_REFRESH_TOKEN;
const REVIEW_SHEET_ID='1KnC56IWf2hRxrGU4ksdO-JlzWyl2XJbhbOHKkdx4vms';
for(const [k,v] of Object.entries({CLIENT_ID,CLIENT_SECRET,REFRESH_TOKEN}))if(!v)throw new Error(`${k} no configurado`);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function token(){const b=new URLSearchParams({client_id:CLIENT_ID,client_secret:CLIENT_SECRET,refresh_token:REFRESH_TOKEN,grant_type:'refresh_token'});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:b});const d=await r.json();if(!r.ok||!d.access_token)throw new Error(`OAuth HTTP ${r.status}`);return d.access_token;}
async function read(t,range,render='FORMATTED_VALUE'){const u=`https://sheets.googleapis.com/v4/spreadsheets/${REVIEW_SHEET_ID}/values/${encodeURIComponent(range)}?majorDimension=ROWS&valueRenderOption=${render}`;let last;for(let i=0;i<5;i++){const r=await fetch(u,{headers:{Authorization:`Bearer ${t}`}}),d=await r.json();if(r.ok)return d.values||[];last={status:r.status,msg:d.error?.message||'desconocido'};if(![429,500,502,503,504].includes(r.status)||i===4)break;await sleep(700*(2**i));}throw new Error(`Sheets ${range} HTTP ${last?.status}: ${last?.msg}`);}
async function meta(t){const f=encodeURIComponent('properties(title),sheets(properties(title,index,hidden))');const r=await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${REVIEW_SHEET_ID}?includeGridData=false&fields=${f}`,{headers:{Authorization:`Bearer ${t}`}}),d=await r.json();if(!r.ok)throw new Error(`Metadata HTTP ${r.status}`);return d;}
function col(i){let n=i+1,s='';while(n){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26);}return s;}
function formulas(v){const out=[];v.forEach((row,r)=>row.forEach((x,c)=>{const s=String(x??'').trim();if(s.startsWith('='))out.push({cell:`${col(c)}${r+1}`,formula:s});}));return out;}
function h(v){return(v[0]||[]).map(x=>String(x??'').trim());}
function obj(headers,row){return Object.fromEntries(headers.map((x,i)=>[x,String(row[i]??'').trim()]));}
function safeResponseStats(v){const headers=h(v),rows=v.slice(1).filter(r=>r.some(x=>String(x??'').trim()));return{data_rows:rows.length,columns:headers.map((header,i)=>{const vals=rows.map(r=>String(r[i]??'').trim()).filter(Boolean);const safe=/contenido desea revisar|decisi[oó]n de revisi[oó]n|publicaci[oó]n est[aá] autorizada|autorizaci[oó]n fue verificada|qu[eé] dato se corrige/i.test(header);return{column:col(i),index:i+1,header,non_empty:vals.length,...(safe?{distinct_values:[...new Set(vals)].sort()}: {})};}),occupancy:rows.map((r,n)=>({row:n+2,non_empty_columns:r.map((x,i)=>String(x??'').trim()?col(i):null).filter(Boolean)}))};}

const t=await token(),m=await meta(t),tabs=(m.sheets||[]).map(s=>s.properties?.title).filter(Boolean);
const response=await read(t,"'Respuestas de formulario 1'!A1:Q100"),raw=await read(t,'RAW_FORM_REVISION!A1:J100'),audit=await read(t,'AUDITORIA_REVISION!A1:P100');
const rawF=formulas(await read(t,'RAW_FORM_REVISION!A1:Z20','FORMULA')),auditF=formulas(await read(t,'AUDITORIA_REVISION!A1:P20','FORMULA')),formSpec=await read(t,'FORM_SPEC!A1:I20');
const rh=h(raw),ah=h(audit),stats=safeResponseStats(response);
const rawSafe=raw.slice(1).filter(r=>r.some(x=>String(x??'').trim())).map((r,n)=>{const o=obj(rh,r);return{row:n+2,fecha:o[rh[0]],tipo:o[rh[1]],decision:o[rh[3]],autorizacion_publicacion:o[rh[4]],autorizacion_menores:o[rh[5]],campo_correccion:o[rh[8]],has_nuevo_valor:Boolean(o[rh[9]])};});
const auditSafe=audit.slice(1).filter(r=>r.some(x=>String(x??'').trim())).map((r,n)=>{const o=obj(ah,r);return{row:n+2,id_revision:o.ID_REVISION,fecha:o.FECHA,tipo:o.TIPO_CONTENIDO,decision:o.DECISION,autorizacion_publicacion:o.AUTORIZACION_PUBLICACION,autorizacion_menores:o.AUTORIZACION_MENORES,estado_proceso:o.ESTADO_PROCESO,id_resuelto:o.ID_RESUELTO,coincidencias:o.COINCIDENCIAS,resultado:o.RESULTADO,campo_correccion:o.CAMPO_CORRECCION,has_nuevo_valor:Boolean(o.NUEVO_VALOR)};});
const report={ok:true,mode:'READ_ONLY_REVIEW_LINEAGE_SANITIZED',timestamp:new Date().toISOString(),spreadsheet_title:m.properties?.title||null,tabs,response_headers:h(response),raw_headers:rh,audit_headers:ah,raw_formulas:rawF,audit_formulas:auditF,response_schema_stats:stats,raw_rows_sanitized:rawSafe,audit_rows_sanitized:auditSafe,form_spec:formSpec};
fs.mkdirSync('qa-review-probe',{recursive:true});fs.writeFileSync('qa-review-probe/read-only-report.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({ok:true,raw_rows:rawSafe,audit_rows:auditSafe,raw_formulas:rawF,audit_formulas:auditF},null,2));
