(()=>{
const API='https://cudo-sports-event-bus.carlos-valdes-morales.workers.dev';
const FALLBACK='../data/championship-fixture.json';
const SERIES_DATA='../data/anfa-chepica-2026-series-results.json';
const CREST_CHUNKS=['../media/crest-base64/0.txt','../media/crest-base64/1.txt','../media/crest-base64/2a.txt','../media/crest-base64/2b.txt'];
const ASSET_VERSION='20260908-1945';
const ROMAN={1:'I',2:'II',3:'III',4:'IV',5:'V'};
const SERIES_LABEL={TERCERA:'Tercera Serie',SEGUNDA:'Segunda Serie',SENIOR:'Senior',PRIMERA:'Primera Serie'};
const CRESTS=new Map([['JUVENTUD DE CHÉPICA',0],['JUVENTUD DE CHEPICA',0],['SANTA ELENA LA RUDA',1],['INDEPENDIENTE',2],['UNIÓN ORILLA',3],['UNION ORILLA',3],['CUDO',3],['SAN JUAN',4],['PEÑAROL LA MINA',5],['PENAROL LA MINA',5],['HURACÁN',6],['HURACAN',6],['SAN AGUSTÍN',7],['SAN AGUSTIN',7],['SAN RAMÓN',8],['SAN RAMON',8],['LAS PALMERAS',9],['LAS CRUCES',10]]);
const norm=n=>(n||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/\s+/g,' ').trim();
const crestIndex=n=>{for(const [k,v] of CRESTS){if(norm(k)===norm(n))return v}return null};
const roundNo=m=>{if(Number(m.round_no))return Number(m.round_no);const x=(m.round_label||'').match(/(IV|III|II|I|V|\d+)/i);if(!x)return 99;const t=x[1].toUpperCase();return({I:1,II:2,III:3,IV:4,V:5}[t]||Number(t)||99)};
const groupOf=m=>String(m.group_id||((m.match_id||'').startsWith('B-')?'B':'A')).toUpperCase();
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c));
function crest(name){const i=crestIndex(name);return i===null?`<span class="champ-crest crest-fallback" aria-label="Escudo de ${esc(name)}">⚽</span>`:`<span class="champ-crest crest-${i}" role="img" aria-label="Escudo de ${esc(name)}"></span>`}
function seriesRows(result){if(!result?.series?.length)return '<div class="champ-series-empty">⚪ Resultados aún no publicados</div>';return `<div class="champ-series" aria-label="Resultados por serie">${result.series.map(s=>`<div class="champ-series-row"><span>${esc(SERIES_LABEL[s.series]||s.series)}</span><strong>${s.home_score} <em>–</em> ${s.away_score}</strong></div>`).join('')}</div><div class="champ-verified">✓ Resultado oficial publicado</div>`}
function matchCard(m,seriesMap){const result=seriesMap.get(m.match_id);return `<article class="champ-match-card ${result?'has-results':''}"><div class="champ-match-head"><div class="champ-team">${crest(m.home_name)}<span class="champ-team-name">${esc(m.home_name)}</span></div><div class="champ-vs">VS</div><div class="champ-team away"><span class="champ-team-name">${esc(m.away_name)}</span>${crest(m.away_name)}</div></div>${seriesRows(result)}</article>`}
async function loadCrestSprite(){const parts=await Promise.all(CREST_CHUNKS.map(async p=>{const r=await fetch(`${p}?v=${ASSET_VERSION}`,{cache:'no-store'});if(!r.ok)throw new Error(`crest_chunk_${r.status}`);return(await r.text()).trim()}));const b64=parts.join('');if(b64.length!==13296||!b64.startsWith('UklGR'))throw new Error(`crest_base64_invalid_${b64.length}`);const data=`data:image/webp;base64,${b64}`;const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(new Error('crest_decode_failed'));img.src=data});if(img.naturalWidth!==224||img.naturalHeight!==168)throw new Error(`crest_dimensions_${img.naturalWidth}x${img.naturalHeight}`);document.documentElement.style.setProperty('--champ-crest-image',`url("${data}")`)}
async function loadData(){let fixture;try{const r=await fetch(`${API}/api/v1/matches`,{cache:'no-store'});if(!r.ok)throw new Error('sports_bus_unavailable');const j=await r.json();const matches=(j.matches||[]).filter(m=>m.competition_id==='ANFA-CHEPICA-2026');if(matches.length!==25)throw new Error('incomplete_bus_fixture');fixture={matches,byes:[],mode:'live'}}catch{const r=await fetch(FALLBACK,{cache:'no-store'});if(!r.ok)throw new Error('fixture_fallback_unavailable');const j=await r.json();fixture={matches:j.matches||[],byes:j.byes||[],mode:'snapshot'}}const sr=await fetch(`${SERIES_DATA}?v=${ASSET_VERSION}`,{cache:'no-store'});const sj=sr.ok?await sr.json():{results:[]};fixture.seriesResults=sj.results||[];return fixture}
function render(matches,byes,seriesResults){let round=1,group='A';const seriesMap=new Map(seriesResults.map(r=>[r.match_id,r]));const available=[...new Set(matches.map(roundNo).filter(n=>n<90))].sort((a,b)=>a-b);const draw=()=>{document.querySelectorAll('.champ-date-btn').forEach(b=>b.classList.toggle('active',Number(b.dataset.round)===round));document.querySelectorAll('.champ-group-btn').forEach(b=>b.classList.toggle('active',b.dataset.group===group));document.getElementById('champRoundTitle').textContent=`FECHA ${ROMAN[round]||round}`;const list=document.getElementById('champMatchList');const rows=matches.filter(m=>roundNo(m)===round&&groupOf(m)===group);list.innerHTML=rows.length?rows.map(m=>matchCard(m,seriesMap)).join(''):'<div class="champ-status">No hay partidos registrados para esta selección.</div>';const bye=byes.find(b=>Number(b.round_no)===round&&String(b.group_id||'').toUpperCase()===group);document.getElementById('champBye')?.remove();if(bye)list.insertAdjacentHTML('afterend',`<div class="champ-bye" id="champBye">🛋️ Descansa: <strong>${esc(bye.team_name||bye.team_id)}</strong></div>`)};document.getElementById('champDateTabs').innerHTML=available.map(n=>`<button class="champ-date-btn ${n===round?'active':''}" data-round="${n}" type="button">Fecha ${ROMAN[n]||n}</button>`).join('');document.getElementById('champPublished').textContent=round===1?'Resultados oficiales disponibles por serie · 23 agosto 2026':'Fixture programado · resultados pendientes';};document.getElementById('champDateTabs').addEventListener('click',e=>{const b=e.target.closest('[data-round]');if(!b)return;round=Number(b.dataset.round);draw()});document.getElementById('champGroupSwitch').addEventListener('click',e=>{const b=e.target.closest('[data-group]');if(!b)return;group=b.dataset.group;draw()});document.querySelector('[data-action="current"]')?.addEventListener('click',()=>{round=1;draw();document.getElementById('champFixture')?.scrollIntoView({behavior:'smooth'})});document.querySelector('[data-action="all"]')?.addEventListener('click',()=>document.getElementById('champFixture')?.scrollIntoView({behavior:'smooth'}));draw()}
async function boot(){if(!document.getElementById('championshipApp'))return;try{await loadCrestSprite();const data=await loadData();render(data.matches,data.byes,data.seriesResults);document.getElementById('champCount').textContent=`${data.matches.length} partidos · ${data.seriesResults.length} con resultados oficiales`;document.getElementById('champLive').textContent=data.mode==='live'?'Fixture conectado al Sports Event Bus':'Fixture oficial publicado · sincronización segura';}catch(err){console.error('championship_boot',err);document.getElementById('champMatchList').innerHTML='<div class="champ-status">No pudimos cargar el campeonato en este momento.</div>';document.getElementById('champLive').textContent='Datos no disponibles';}}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot):boot();
})();