(()=>{
const API='https://cudo-sports-event-bus.carlos-valdes-morales.workers.dev',FALLBACK='../data/championship-fixture.json',SERIES_DATA='../data/anfa-chepica-2026-series-results.json',CREST_CHUNKS=['../media/crest-base64/0.txt','../media/crest-base64/1.txt','../media/crest-base64/2a.txt','../media/crest-base64/2b.txt'],V='20260908-2000';
const ROMAN={1:'I',2:'II',3:'III',4:'IV',5:'V'},LABEL={TERCERA:'Tercera Serie',SEGUNDA:'Segunda Serie',SENIOR:'Senior',PRIMERA:'Primera Serie'};
const NAMES=[['JUVENTUD DE CHEPICA',0],['SANTA ELENA LA RUDA',1],['INDEPENDIENTE',2],['UNION ORILLA',3],['CUDO',3],['SAN JUAN',4],['PENAROL LA MINA',5],['HURACAN',6],['SAN AGUSTIN',7],['SAN RAMON',8],['LAS PALMERAS',9],['LAS CRUCES',10]];
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().trim(),esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c));
const ci=n=>NAMES.find(x=>x[0]===norm(n))?.[1],rn=m=>Number(m.round_no)||({I:1,II:2,III:3,IV:4,V:5}[(m.round_label||'').replace('Fecha ','').trim()]||99),grp=m=>String(m.group_id||((m.match_id||'').startsWith('B-')?'B':'A')).toUpperCase();
function crest(n){const i=ci(n);return i===undefined?'<span class="champ-crest crest-fallback">⚽</span>':`<span class="champ-crest crest-${i}" role="img" aria-label="Escudo ${esc(n)}"></span>`}
function card(m,map){const r=map.get(m.match_id),series=r?.series?.length?`<div class="champ-series">${r.series.map(s=>`<div class="champ-series-row"><span>${LABEL[s.series]||s.series}</span><strong>${s.home_score}<em>–</em>${s.away_score}</strong></div>`).join('')}</div><div class="champ-verified">✓ Resultado oficial publicado</div>`:'<div class="champ-series-empty">⚪ Resultados aún no publicados</div>';return `<article class="champ-match-card ${r?'has-results':''}"><div class="champ-match-head"><div class="champ-team">${crest(m.home_name)}<span class="champ-team-name">${esc(m.home_name)}</span></div><div class="champ-vs">VS</div><div class="champ-team away"><span class="champ-team-name">${esc(m.away_name)}</span>${crest(m.away_name)}</div></div>${series}</article>`}
async function sprite(){const p=await Promise.all(CREST_CHUNKS.map(async x=>{const r=await fetch(`${x}?v=${V}`,{cache:'no-store'});if(!r.ok)throw Error('crest');return(await r.text()).trim()})),b=p.join('');if(b.length!==13296)throw Error('crest_length');const data=`data:image/webp;base64,${b}`;document.documentElement.style.setProperty('--champ-crest-image',`url("${data}")`)}
async function data(){let f;try{const r=await fetch(`${API}/api/v1/matches`,{cache:'no-store'}),j=await r.json(),m=(j.matches||[]).filter(x=>x.competition_id==='ANFA-CHEPICA-2026');if(m.length!==25)throw Error('fixture');f={matches:m,byes:[],mode:'live'}}catch(e){const r=await fetch(`${FALLBACK}?v=${V}`,{cache:'no-store'}),j=await r.json();f={matches:j.matches||[],byes:j.byes||[],mode:'snapshot'}}const r=await fetch(`${SERIES_DATA}?v=${V}`,{cache:'no-store'}),j=r.ok?await r.json():{results:[]};f.results=j.results||[];return f}
function render(d){let round=1,group='A';const map=new Map(d.results.map(x=>[x.match_id,x])),available=[...new Set(d.matches.map(rn).filter(x=>x<90))].sort();const draw=()=>{document.getElementById('champRoundTitle').textContent=`FECHA ${ROMAN[round]}`;document.querySelectorAll('.champ-date-btn').forEach(x=>x.classList.toggle('active',+x.dataset.round===round));document.querySelectorAll('.champ-group-btn').forEach(x=>x.classList.toggle('active',x.dataset.group===group));const rows=d.matches.filter(x=>rn(x)===round&&grp(x)===group);document.getElementById('champMatchList').innerHTML=rows.map(x=>card(x,map)).join('')||'<div class="champ-status">Sin partidos.</div>';document.getElementById('champPublished').textContent=round===1?'Resultados oficiales disponibles por serie · 23 agosto 2026':'Fixture programado · resultados pendientes'};document.getElementById('champDateTabs').innerHTML=available.map(n=>`<button class="champ-date-btn ${n===1?'active':''}" data-round="${n}">Fecha ${ROMAN[n]}</button>`).join('');document.getElementById('champDateTabs').onclick=e=>{const b=e.target.closest('[data-round]');if(b){round=+b.dataset.round;draw()}};document.getElementById('champGroupSwitch').onclick=e=>{const b=e.target.closest('[data-group]');if(b){group=b.dataset.group;draw()}};document.querySelector('[data-action="current"]')?.addEventListener('click',()=>{round=1;draw();document.getElementById('champFixture').scrollIntoView({behavior:'smooth'})});draw();document.getElementById('champCount').textContent=`${d.matches.length} partidos · ${d.results.length} con resultados oficiales`;document.getElementById('champLive').textContent=d.mode==='live'?'Fixture conectado al Sports Event Bus':'Fixture oficial publicado · sincronización segura'}
async function boot(){if(!document.getElementById('championshipApp'))return;sprite().catch(e=>console.warn('crest_asset',e));try{render(await data())}catch(e){console.error('championship_data',e);document.getElementById('champMatchList').innerHTML='<div class="champ-status">No pudimos cargar el campeonato.</div>'}}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot):boot();
})();