const fs = require('fs');
const path = require('path');
const { google } = require('googleapis');

const REQUIRED_QA_KEYS = ['QA_NOTICIAS','QA_EQUIPOS','QA_PLANTEL','QA_PARTIDOS','QA_TABLA','QA_GALERIA'];
function requiredEnv(name){const value=process.env[name];if(!value||!String(value).trim())throw new Error(`${name} no está configurado`);return String(value).trim();}
function buildOAuthClient(){const auth=new google.auth.OAuth2(requiredEnv('CUDO_GOOGLE_OAUTH_CLIENT_ID'),requiredEnv('CUDO_GOOGLE_OAUTH_CLIENT_SECRET'));auth.setCredentials({refresh_token:requiredEnv('CUDO_GOOGLE_REFRESH_TOKEN')});return auth;}
function loadAppsScriptFiles(baseDir){const files=[];for(const entry of fs.readdirSync(baseDir,{withFileTypes:true})){if(entry.isFile()&&entry.name.endsWith('.gs'))files.push({name:path.basename(entry.name,'.gs'),type:'SERVER_JS',source:fs.readFileSync(path.join(baseDir,entry.name),'utf8')});}const manifestPath=path.join(baseDir,'appsscript.json');if(!fs.existsSync(manifestPath))throw new Error('Falta appsscript.json');files.push({name:'appsscript',type:'JSON',source:fs.readFileSync(manifestPath,'utf8')});return files;}
function hasExecutionApi(deployment){return (deployment?.entryPoints||[]).some(ep=>ep.entryPointType==='EXECUTION_API');}
function validateProvisionResult(result){if(!result||typeof result!=='object'||Array.isArray(result))throw new Error('provisionAllQA no devolvió resultados');const failures=[];for(const key of REQUIRED_QA_KEYS){const item=result[key];if(!item||item.ERROR||!item.FORM_ID||!item.FORM_RESPONDER_URL||!item.LINKED_SPREADSHEET_ID)failures.push(`${key}: ${item?.ERROR||'metadata incompleta'}`)}if(failures.length)throw new Error(`Validación QA falló:\n${failures.join('\n')}`);}
function validateSingleForm(name,item){if(!item||typeof item!=='object'||item.ERROR||!item.FORM_ID||!item.FORM_RESPONDER_URL||!item.LINKED_SPREADSHEET_ID||item.ESTADO!=='ACEPTANDO_RESPUESTAS')throw new Error(`${name}: metadata incompleta o formulario cerrado`);}
async function resolveExecutableDeployment(script,scriptId,preferredId,versionNumber,description){const listed=await script.projects.deployments.list({scriptId});const deployments=listed.data.deployments||[];let selected=preferredId?deployments.find(d=>d.deploymentId===preferredId&&hasExecutionApi(d)):null;if(!selected)selected=deployments.find(hasExecutionApi)||null;if(selected){await script.projects.deployments.update({scriptId,deploymentId:selected.deploymentId,requestBody:{deploymentConfig:{scriptId,versionNumber,manifestFileName:'appsscript',description}}});return (await script.projects.deployments.get({scriptId,deploymentId:selected.deploymentId})).data;}return (await script.projects.deployments.create({scriptId,requestBody:{versionNumber,manifestFileName:'appsscript',description}})).data;}
async function runFunction(script,deploymentId,fn){const execution=await script.scripts.run({scriptId:deploymentId,requestBody:{function:fn,devMode:false}});if(execution.data.error)throw new Error(`${fn} devolvió error: ${JSON.stringify(execution.data.error.details||execution.data.error)}`);return execution.data.response&&execution.data.response.result;}

async function main(){
 const scriptId=requiredEnv('CUDO_APPS_SCRIPT_ID'),preferred=String(process.env.CUDO_APPS_SCRIPT_DEPLOYMENT_ID||'').trim(),auth=buildOAuthClient(),script=google.script({version:'v1',auth}),description=`CUDO QA auto ${process.env.GITHUB_SHA||new Date().toISOString()}`;
 console.log('[1/9] Validando proyecto Apps Script...');const project=await script.projects.get({scriptId});if(project.data.scriptId!==scriptId)throw new Error('Script ID no coincide');
 console.log('[2/9] Actualizando HEAD...');await script.projects.updateContent({scriptId,requestBody:{files:loadAppsScriptFiles(__dirname)}});
 console.log('[3/9] Versionando y resolviendo deployment...');const version=await script.projects.versions.create({scriptId,requestBody:{description}}),versionNumber=version.data.versionNumber,deployment=await resolveExecutableDeployment(script,scriptId,preferred,versionNumber,description),deploymentId=deployment.deploymentId;
 console.log('[4/9] Provisionando seis dominios visibles...');const result=await runFunction(script,deploymentId,'provisionAllQA');validateProvisionResult(result);
 console.log('[5/9] Aplicando ramificación humana de Partidos...');const partidosBranching=await runFunction(script,deploymentId,'ensurePartidosBranchingQA');if(!partidosBranching?.ok||partidosBranching.pages?.length!==2||partidosBranching.choices?.length!==4)throw new Error(`Ramificación Partidos inválida: ${JSON.stringify(partidosBranching)}`);
 console.log('[6/9] Provisionando mantenimiento humano...');const maintenance=await runFunction(script,deploymentId,'provisionMantenimientoQA');validateSingleForm('QA_MANTENIMIENTO',maintenance);
 console.log('[7/9] Provisionando revisión humana...');const review=await runFunction(script,deploymentId,'provisionRevisionQA');validateSingleForm('QA_REVISION',review);
 console.log('[8/9] Procesando cola de revisiones pendientes...');const reviewQueue=await runFunction(script,deploymentId,'processPendingReviewsQA');if(!reviewQueue||typeof reviewQueue!=='object'||Number(reviewQueue.error||0)>0)throw new Error(`Cola inválida: ${JSON.stringify(reviewQueue)}`);
 console.log('[9/9] QA básico completo.');console.log(JSON.stringify({ok:true,scriptId,deploymentId,versionNumber,result,partidosBranching,maintenance,review,reviewQueue},null,2));
}
main().catch(err=>{const status=err?.response?.status,data=err?.response?.data;console.error('CUDO QA Forms Auto ERROR:',status?`HTTP ${status}`:'',data||err.message||err);process.exit(1);});
